language: node_js
node_js:
  - stable
before_install:
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install yarn -y
install:
  - yarn install
script:
  - yarn run test
  - yarn run build #TODO: убрать, когда сделаем тестирование в DOM
  - yarn run lint
  - yarn run stylelint
after_success:
  - yarn run push-coverage
cache:
  directories:
    - node_modules
