language: node_js
node_js:
  - stable
install:
  - npm install --global yarn
  - yarn install
# TODO: use yarn for run scripts. yarn can't run scripts with spaces %)
script:
  - npm run test
  - npm run build #TODO: убрать, когда сделаем тестирование в DOM
  - npm run lint
  - npm run stylelint
after_success:
  - npm run push-coverage
cache:
  directories:
    - node_modules
