language: node_js
node_js:
  - stable
install:
  - npm install --global yarn
  - yarn install
script:
  - yarn run test
  - yarn run build #TODO: убрать, когда сделаем тестирование в DOM
  - yarn run lint
  - yarn run stylelint
after_success:
  - yarn run push-coverage
cache:
  directories:
    - node_modules
